[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "yebi"
authors = [{name = "Daniel", email = "daniel.pratt@unarlabs.com"}]
dynamic = ["version", "description"]
